# Generated by Django 4.2.7 on 2024-01-02 17:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Reader', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('img', models.ImageField(upload_to='')),
                ('borrow_price', models.IntegerField()),
                ('book_borrower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_borrower', to='Reader.reader')),
            ],
        ),
    ]
