# Generated by Django 4.2.7 on 2024-01-03 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Category', '0002_category_slug'),
        ('Books', '0004_alter_books_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='books',
            name='book_borrower',
        ),
        migrations.AlterField(
            model_name='books',
            name='category',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Category.category'),
        ),
    ]
