# Generated by Django 4.2.7 on 2024-01-02 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reader', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reader',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='posts/media/uploads/'),
        ),
    ]
