# Generated by Django 4.2.7 on 2024-01-03 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0005_remove_books_book_borrower_alter_books_category'),
        ('Reader', '0002_alter_reader_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='Borrow_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_date', models.DateTimeField(auto_now_add=True)),
                ('IsBorrowed', models.BooleanField(default=False)),
                ('book', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Books.books')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Reader.reader')),
            ],
        ),
    ]
