# Generated by Django 4.2.7 on 2024-01-03 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Reader', '0003_borrow_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reader',
            name='img',
        ),
    ]
