# Generated by Django 4.2.7 on 2024-01-04 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reader', '0005_alter_borrow_model_isborrowed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reader',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
