# Generated by Django 4.2.7 on 2024-02-27 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reader', '0006_reader_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrow_model',
            name='IsBorrowed',
            field=models.BooleanField(default=True),
        ),
    ]
